# Generated by Django 3.2.11 on 2022-10-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalslist', '0002_sittinglist_breeds_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sittinglist',
            name='animals_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animalslist.animalslist'),
        ),
        migrations.AlterField(
            model_name='sittinglist',
            name='breeds_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animalslist.breedlist'),
        ),
    ]
