# Generated by Django 3.2.11 on 2022-10-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalslist', '0003_auto_20221011_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sittinglist',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
